import {useEffect,useState} from 'react';
import {AlertTriangle,Clock3,Code2,Download,Printer,ShieldCheck,TerminalSquare} from 'lucide-react';
import {useSearchParams} from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import ScoreRing from '../components/ScoreRing';
import StatusBadge from '../components/StatusBadge';
import MetricsGrid from '../components/MetricsGrid';
import {api,apiMessage} from '../services/api';
import {downloadVerificationReport,printVerificationReport} from '../utils/verificationReport';

export default function ResultsPage(){
  const[params]=useSearchParams(),id=params.get('id'),[data,setData]=useState(null),[error,setError]=useState('');
  useEffect(()=>{if(id)api.get(`/translations/${id}`).then(r=>setData(r.data)).catch(e=>setError(apiMessage(e)));},[id]);
  if(!id)return <Empty message="Open a saved translation from History."/>;
  if(error)return <div className="rounded-2xl bg-rose-50 p-5 text-rose-700">{error}</div>;
  if(!data)return <div className="p-10 text-center text-slate-500">Loading result…</div>;
  const{translation:t,verification:v,tests=[]}=data; const failed=tests.filter(x=>!['PASS','PASSED','VERIFIED'].includes(String(x.status||'').toUpperCase()));
  const explanation=v?.executionUnavailable?'Execution infrastructure was unavailable, so the saved run should not be treated as behaviorally verified.':failed.length?`${failed.length} test case(s) failed or errored. Inspect the input, expected output, actual output, and error message for the affected cases.`:((v?.score??t.verificationScore??0)<100?'The run completed, but not every comparable test passed. Review the AI findings and failing evidence before accepting the migration.':'All comparable tests passed and the saved run contains behavioral evidence for this migration.');
  return <div className="mx-auto max-w-7xl">
    <div className="flex flex-wrap items-start justify-between gap-4"><PageHeader eyebrow="Verification result" title={`${t.sourceLanguage} → ${t.targetLanguage}`} description="Detailed evidence from the saved migration run."/><div className="flex gap-2"><button onClick={()=>downloadVerificationReport({translation:t,verification:v,tests})} className="mt-1 inline-flex items-center gap-2 rounded-xl border border-sky-200 bg-sky-50 px-3 py-2 text-sm font-bold text-sky-700 dark:border-sky-400/20 dark:bg-sky-400/10 dark:text-sky-300"><Download size={16}/> Report</button><button onClick={()=>printVerificationReport({translation:t,verification:v,tests})} className="mt-1 inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold text-slate-700 dark:border-slate-700 dark:bg-[#111a2c] dark:text-slate-200"><Printer size={16}/> Print / PDF</button></div></div>
    <div className="mb-5"><MetricsGrid verification={v}/></div>
    <div className="grid gap-5 lg:grid-cols-[250px_1fr]">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-[#111a2c]"><div className="flex justify-center"><ScoreRing score={v?.score??t.verificationScore??0} label="verification"/></div><div className="mt-4 text-center"><StatusBadge status={t.status}/></div><div className="mt-5 space-y-3 text-sm"><Metric icon={ShieldCheck} label="Passed tests" value={`${v?.passedTests??0}/${v?.totalTests??0}`}/><Metric icon={TerminalSquare} label="Compilation errors" value={v?.compilationErrors??0}/><Metric icon={Code2} label="Runtime errors" value={v?.runtimeErrors??0}/><Metric icon={Clock3} label="Execution" value={`${v?.executionTime??0} ms`}/></div>{v?.executionUnavailable&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-800 dark:border-amber-400/20 dark:bg-amber-400/10 dark:text-amber-200">Execution infrastructure was unavailable. No behavioral verification claim was made.</div>}</section>
      <div className="space-y-5"><section className="grid gap-5 xl:grid-cols-2"><Code title="Source code" value={t.sourceCode}/><Code title="Generated code" value={t.generatedCode}/></section>{((v?.score??0)<100||failed.length||v?.executionUnavailable)&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-400/20 dark:bg-amber-400/10"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 shrink-0 text-amber-600 dark:text-amber-300"/><div><h2 className="font-extrabold text-amber-900 dark:text-amber-100">Why verification needs review</h2><p className="mt-1 text-sm leading-6 text-amber-800 dark:text-amber-200">{explanation}</p></div></div></section>}
        <section className="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-[#111a2c]"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 dark:border-slate-800"><h2 className="font-extrabold">Test cases</h2><span className="text-xs text-slate-500">AI confidence {v?.aiConfidence!=null?`${Math.round(v.aiConfidence*100)}%`:'—'}</span></div><div className="overflow-auto"><table className="w-full min-w-[820px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-[#0c1526]"><tr><th className="px-5 py-3 text-left">Test</th><th className="px-5 py-3 text-left">Input</th><th className="px-5 py-3 text-left">Expected</th><th className="px-5 py-3 text-left">Actual</th><th className="px-5 py-3 text-left">Status</th><th className="px-5 py-3 text-left">Error</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{tests.map(t=><tr key={t._id||t.name}><td className="px-5 py-3 font-bold">{t.name}</td><td className="px-5 py-3 font-mono text-xs">{t.input}</td><td className="px-5 py-3 font-mono text-xs">{t.expectedOutput??t.originalOutput}</td><td className="px-5 py-3 font-mono text-xs">{t.actualOutput??t.translatedOutput}</td><td className="px-5 py-3"><StatusBadge status={t.status}/></td><td className="max-w-[280px] px-5 py-3 text-xs text-rose-600 dark:text-rose-300">{t.error||'—'}</td></tr>)}</tbody></table></div></section></div>
    </div>
  </div>
}
function Metric({icon:Icon,label,value}){return <div className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2.5 dark:bg-[#0c1526]"><span className="flex items-center gap-2 text-xs text-slate-500"><Icon size={14}/>{label}</span><b>{value}</b></div>}
function Code({title,value}){return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-[#0f172a] shadow-sm dark:border-slate-800"><div className="border-b border-white/10 bg-[#111c31] px-4 py-3 text-xs font-extrabold uppercase tracking-wider text-slate-300">{title}</div><pre className="scrollbar-thin max-h-[430px] overflow-auto p-4 text-xs leading-6 text-slate-200"><code>{value}</code></pre></section>}
function Empty({message}){return <div className="rounded-2xl border border-dashed border-slate-300 p-12 text-center text-slate-500">{message}</div>}
