import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,ClipboardCheck,Download,LoaderCircle,Printer,Save,Sparkles,Trash2,AlertTriangle} from 'lucide-react';
import PageHeader from '../components/PageHeader';
import CodeEditor from '../components/CodeEditor';
import ScoreRing from '../components/ScoreRing';
import StatusBadge from '../components/StatusBadge';
import ProgressSteps from '../components/ProgressSteps';
import MetricsGrid from '../components/MetricsGrid';
import {api,apiMessage} from '../services/api';
import {useTheme} from '../context/ThemeContext';
import {useLocation} from 'react-router-dom';
import {downloadVerificationReport,printVerificationReport} from '../utils/verificationReport';

const sample=`#include <stdio.h>\nint main(){\n  int a,b;\n  if(scanf("%d %d", &a, &b)!=2) return 0;\n  printf("%d\\n", a+b);\n  return 0;\n}`;
const steps=['Analyzing source code...','Generating target code...','AI reviewing translation...','Compiling source...','Running source tests...','Compiling target...','Running target tests...','Comparing outputs...','Generating verification report...'];

export default function TranslatePage(){
  const{theme}=useTheme(); const location=useLocation(); const incomingSample=location.state?.sample;
  const[pairs,setPairs]=useState([]),[source,setSource]=useState('C'),[target,setTarget]=useState('Java'),[code,setCode]=useState(sample),[result,setResult]=useState(null),[loading,setLoading]=useState(false),[current,setCurrent]=useState(0),[error,setError]=useState('');
  useEffect(()=>{api.get('/languages/pairs').then(r=>setPairs(r.data.pairs)).catch(()=>{})},[]);
  useEffect(()=>{if(!incomingSample)return;setSource(incomingSample.sourceLanguage||'C');setTarget(incomingSample.targetLanguage||'Java');setCode(incomingSample.sourceCode||'');setResult(null);},[incomingSample]);
  const targets=useMemo(()=>pairs.filter(p=>p.sourceLanguage===source).map(p=>p.targetLanguage),[pairs,source]);
  useEffect(()=>{if(!targets.includes(target)&&targets[0])setTarget(targets[0])},[targets]);
  const run=async()=>{setLoading(true);setError('');setResult(null);setCurrent(0);let i=0;const timer=setInterval(()=>{i=Math.min(i+1,8);setCurrent(i)},650);try{const r=await api.post('/translations/run',{sourceLanguage:source,targetLanguage:target,sourceCode:code,userTests:[]});setResult(r.data.result);setCurrent(8)}catch(e){setError(apiMessage(e,'Translation pipeline failed. Check Clerk/API configuration and the server logs.'))}finally{clearInterval(timer);setLoading(false)}};
  const save=async()=>{if(!result)return;try{await api.post('/translations',result);alert('Result saved to History.')}catch(e){setError(apiMessage(e,'Unable to save result.'))}};
  const verification=result?.verification||{}; const tests=verification.results||result?.testCases||[]; const failed=tests.filter(t=>!['PASS','PASSED','VERIFIED'].includes(String(t.status||'').toUpperCase()));
  const explain=verification.executionUnavailable?'Execution sandbox was unavailable, so behavioral verification was not established.':failed.length?`${failed.length} test case(s) failed or errored. Review the detailed evidence below and compare the original and translated outputs.`:'All comparable tests passed. The translation has behavioral evidence for the executed cases.';
  return <div className="mx-auto max-w-[1500px]">
    <PageHeader eyebrow="Translator" title="Legacy code migration" description="Paste source code, select the language pair, then run the complete translation → review → execution → comparison pipeline."/>
    <div className="mb-5 grid gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_auto_1fr] md:items-end dark:border-slate-800 dark:bg-[#111a2c]">
      <label><span className="mb-1.5 block text-xs font-extrabold uppercase tracking-wider text-slate-500">Source language</span><select value={source} onChange={e=>setSource(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold dark:border-slate-700 dark:bg-[#0c1526]">{[...new Set(pairs.map(p=>p.sourceLanguage))].map(x=><option key={x}>{x}</option>)}</select></label>
      <div className="hidden items-center justify-center md:flex"><div className="grid h-11 w-11 place-items-center rounded-full bg-violet-50 text-violet-600 dark:bg-violet-400/10"><ArrowRight/></div></div>
      <label><span className="mb-1.5 block text-xs font-extrabold uppercase tracking-wider text-slate-500">Target language</span><select value={target} onChange={e=>setTarget(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold dark:border-slate-700 dark:bg-[#0c1526]">{targets.map(x=><option key={x}>{x}</option>)}</select></label>
    </div>
    {error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700 dark:border-rose-400/20 dark:bg-rose-400/10 dark:text-rose-300">{error}</div>}
    {loading&&<div className="mb-5 grid gap-4 rounded-2xl border border-violet-100 bg-white p-5 shadow-sm lg:grid-cols-[1fr_320px] dark:border-violet-400/10 dark:bg-[#111a2c]"><div><div className="mb-4 flex items-center gap-2 text-sm font-bold text-violet-700 dark:text-violet-300"><LoaderCircle className="animate-spin-slow" size={18}/> Running verification pipeline</div><ProgressSteps steps={steps} current={current}/></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-[#0c1526]"><div className="text-xs font-bold uppercase tracking-widest text-slate-500">Why this matters</div><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">AI generates and reviews the code, but behavioral evidence comes from executing both programs with the same inputs.</p></div></div>}
    <div className="grid gap-5 xl:grid-cols-2"><CodeEditor label="Source code" language={source} value={code} onChange={setCode} onClear={()=>setCode('')} onCopy={()=>navigator.clipboard?.writeText(code)} theme={theme}/><CodeEditor label={result?'Generated code':'Generated code will appear here'} language={target} value={result?.generatedCode||''} onChange={()=>{}} readOnly onCopy={()=>navigator.clipboard?.writeText(result?.generatedCode||'')} theme={theme}/></div>
    <div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" disabled={loading} onClick={run} aria-busy={loading} className={`translate-verify-btn inline-flex items-center gap-2 rounded-xl px-5 py-3 text-sm font-extrabold text-white shadow-lg focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-violet-300/50 disabled:cursor-not-allowed ${loading?'is-loading':''}`}>{loading?<LoaderCircle size={17} className="translate-verify-spinner"/>:<Sparkles size={17}/>}<span>{loading?'Running verification…':'Translate & Verify'}</span></button><button onClick={()=>{setCode('');setResult(null)}} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 dark:border-slate-700 dark:bg-[#111a2c] dark:text-slate-200"><Trash2 size={16}/> Clear</button>{result&&<><button onClick={save} className="inline-flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700 dark:border-emerald-400/20 dark:bg-emerald-400/10 dark:text-emerald-300"><Save size={16}/> Save Result</button><button onClick={()=>downloadVerificationReport({translation:result,verification,tests})} className="inline-flex items-center gap-2 rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm font-bold text-sky-700 dark:border-sky-400/20 dark:bg-sky-400/10 dark:text-sky-300"><Download size={16}/> Download Report</button><button onClick={()=>printVerificationReport({translation:result,verification,tests})} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 dark:border-slate-700 dark:bg-[#111a2c] dark:text-slate-200"><Printer size={16}/> Print / Save PDF</button></>}</div>
    {result&&<div className="mt-6 space-y-5"><MetricsGrid verification={verification}/><section className="grid gap-5 lg:grid-cols-[240px_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-[#111a2c]"><div className="flex justify-center"><ScoreRing score={verification.score||0} label="behavioral"/></div><div className="mt-4 text-center"><StatusBadge status={verification.status}/><div className="mt-2 text-xs text-slate-500">{verification.passedTests}/{verification.totalTests} comparable tests passed</div></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-[#111a2c]"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><ClipboardCheck size={18} className="text-emerald-500"/><h2 className="font-extrabold">AI review</h2></div><p className="mt-1 text-sm text-slate-500">{result.aiProvider} · {result.aiModel}</p></div><div className="rounded-xl bg-slate-50 px-3 py-2 text-right dark:bg-[#0c1526]"><div className="text-[10px] font-bold uppercase tracking-widest text-slate-500">AI confidence</div><div className="text-lg font-extrabold">{Math.round((result.aiReview?.confidence||0)*100)}%</div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Logic preserved',result.aiReview?.logicPreserved],['Syntax reviewed',result.aiReview?.syntaxValid],['I/O reviewed',result.aiReview?.inputOutputEquivalent]].map(([l,v])=><div key={l} className="rounded-xl border border-slate-100 p-3 dark:border-slate-800"><div className="text-xs text-slate-500">{l}</div><div className={`mt-1 font-bold ${v?'text-emerald-600':'text-rose-600'}`}>{v?'Yes':'Needs review'}</div></div>)}</div>{(result.aiReview?.issues||[]).length>0&&<div className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800 dark:bg-amber-400/10 dark:text-amber-200">{result.aiReview.issues.join(' ')}</div>}</div></section>
      {(failed.length>0||verification.executionUnavailable||verification.status!=='VERIFIED')&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-400/20 dark:bg-amber-400/10"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 shrink-0 text-amber-600 dark:text-amber-300"/><div><h2 className="font-extrabold text-amber-900 dark:text-amber-100">Why verification needs review</h2><p className="mt-1 text-sm leading-6 text-amber-800 dark:text-amber-200">{explain}</p></div></div></section>}
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-[#111a2c]"><div className="border-b border-slate-100 px-5 py-4 dark:border-slate-800"><h2 className="font-extrabold">Test case summary</h2></div><div className="overflow-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 dark:bg-[#0c1526]"><tr><th className="px-5 py-3">Test</th><th className="px-5 py-3">Input</th><th className="px-5 py-3">Expected</th><th className="px-5 py-3">Actual</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Time</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{tests.map((t,i)=><tr key={t.name||i}><td className="px-5 py-3 font-bold">{t.name||`TC_${i+1}`}</td><td className="max-w-[200px] truncate px-5 py-3 font-mono text-xs text-slate-600">{t.input}</td><td className="max-w-[220px] truncate px-5 py-3 font-mono text-xs">{t.expectedOutput??t.originalOutput}</td><td className="max-w-[220px] truncate px-5 py-3 font-mono text-xs">{t.actualOutput??t.translatedOutput}</td><td className="px-5 py-3"><StatusBadge status={t.status}/></td><td className="px-5 py-3 text-xs text-slate-500">{t.executionTime||0} ms</td></tr>)}</tbody></table></div></section><div className="flex flex-wrap gap-2 text-xs text-slate-500"><span>Compilation errors: <b>{verification.compilationErrors??0}</b></span><span>Runtime errors: <b>{verification.runtimeErrors??0}</b></span><span>Execution time: <b>{verification.executionTime??0} ms</b></span>{result.demo&&<span className="rounded-full bg-amber-50 px-2 py-1 font-bold text-amber-700">DEMO / fixture data</span>}</div></div>}
  </div>
}
