import TestCase from '../models/TestCase.js';
import Translation from '../models/Translation.js';
import { ExecutionService } from '../services/execution/ExecutionService.js';
import { runVerification } from '../services/verification/VerificationService.js';
import { AppError } from '../utils/errors.js';
async function ownTranslation(id,userId){const t=await Translation.findOne({_id:id,userId});if(!t) throw new AppError('Translation not found.',404,'NOT_FOUND');return t;}
export async function list(req,res){await ownTranslation(req.params.translationId,req.user._id);res.json({success:true,items:await TestCase.find({translationId:req.params.translationId}).sort({createdAt:1}).lean()});}
export async function create(req,res){await ownTranslation(req.body.translationId,req.user._id);res.status(201).json({success:true,testCase:await TestCase.create({...req.body,status:'UNAVAILABLE'})});}
export async function update(req,res){const t=await TestCase.findById(req.params.id);if(!t) throw new AppError('Test case not found.',404,'NOT_FOUND');await ownTranslation(t.translationId,req.user._id);Object.assign(t,req.body);await t.save();res.json({success:true,testCase:t});}
export async function remove(req,res){const t=await TestCase.findById(req.params.id);if(!t) throw new AppError('Test case not found.',404,'NOT_FOUND');await ownTranslation(t.translationId,req.user._id);await t.deleteOne();res.json({success:true});}
export async function runOne(req,res){const t=await TestCase.findById(req.params.id);if(!t) throw new AppError('Test case not found.',404,'NOT_FOUND');const tr=await ownTranslation(t.translationId,req.user._id);const original=await ExecutionService.execute(tr.sourceLanguage,tr.sourceCode,t.input);const target=await ExecutionService.execute(tr.targetLanguage,tr.generatedCode,t.input);const normalized=x=>(x||'').replace(/\r\n/g,'\n').trim();t.originalOutput=original.stdout||'';t.actualOutput=target.stdout||'';t.expectedOutput=t.expectedOutput||original.stdout||'';t.executionTime=(original.executionTime||0)+(target.executionTime||0);t.status=original.status==='COMPILATION_ERROR'||target.status==='COMPILATION_ERROR'?'COMPILATION_ERROR':original.status==='RUNTIME_ERROR'||target.status==='RUNTIME_ERROR'?'RUNTIME_ERROR':normalized(t.expectedOutput)===normalized(t.actualOutput)?'PASS':'FAIL';t.error=t.status==='PASS'?null:(target.stderr||original.stderr||'Outputs differ');await t.save();res.json({success:true,testCase:t});}
export async function runAll(req,res){const tr=await ownTranslation(req.params.translationId,req.user._id);const tests=await TestCase.find({translationId:tr._id}).lean();const result=await runVerification({sourceLanguage:tr.sourceLanguage,targetLanguage:tr.targetLanguage,sourceCode:tr.sourceCode,generatedCode:tr.generatedCode,tests});await TestCase.deleteMany({translationId:tr._id});await TestCase.insertMany(result.results.map((x)=>({translationId:tr._id,...x})));res.json({success:true,verification:result});}
