import Translation from '../models/Translation.js';
import VerificationResult from '../models/VerificationResult.js';
import TestCase from '../models/TestCase.js';
import { runTranslationPipeline } from '../services/translation/TranslationService.js';
import { AppError } from '../utils/errors.js';

export async function run(req,res){const result=await runTranslationPipeline({...req.body,userId:req.user._id});res.json({success:true,result});}
export async function save(req,res){const {sourceLanguage,targetLanguage,sourceCode,generatedCode,aiProvider,aiModel,aiReview,verification}=req.body;if(!sourceCode||!generatedCode) throw new AppError('A translation result is required.',422);const doc=await Translation.create({userId:req.user._id,sourceLanguage,targetLanguage,sourceCode,generatedCode,aiProvider,aiModel,aiReview,verificationScore:verification?.score,status:verification?.status||'AI REVIEW REQUIRED',summary:verification}); if(verification){await VerificationResult.create({translationId:doc._id,score:verification.score,totalTests:verification.totalTests,passedTests:verification.passedTests,failedTests:verification.failedTests,compilationErrors:verification.compilationErrors,runtimeErrors:verification.runtimeErrors,executionTime:verification.executionTime,aiConfidence:aiReview?.confidence||null,evidence:'Executable behavioral comparison'});} for(const tc of (verification?.results||[])){await TestCase.create({translationId:doc._id,...tc});} res.status(201).json({success:true,translation:doc});}
export async function list(req,res){const page=Math.max(1,Number(req.query.page||1)),limit=Math.min(50,Math.max(1,Number(req.query.limit||10))),q=req.query.q||'',filter=q?{userId:req.user._id,$or:[{sourceLanguage:new RegExp(q,'i')},{targetLanguage:new RegExp(q,'i')},{status:new RegExp(q,'i')}]}:{userId:req.user._id};const [items,total]=await Promise.all([Translation.find(filter).sort({createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),Translation.countDocuments(filter)]);res.json({success:true,items,pagination:{page,limit,total,pages:Math.ceil(total/limit)}});}
export async function getOne(req,res){const translation=await Translation.findOne({_id:req.params.id,userId:req.user._id});if(!translation) throw new AppError('Translation not found.',404,'NOT_FOUND');const [tests,verification]=await Promise.all([TestCase.find({translationId:translation._id}).lean(),VerificationResult.findOne({translationId:translation._id}).sort({createdAt:-1}).lean()]);res.json({success:true,translation,tests,verification});}
export async function remove(req,res){const t=await Translation.findOneAndDelete({_id:req.params.id,userId:req.user._id});if(!t) throw new AppError('Translation not found.',404,'NOT_FOUND');await Promise.all([TestCase.deleteMany({translationId:t._id}),VerificationResult.deleteMany({translationId:t._id})]);res.json({success:true});}
